version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: panteon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - panteon_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6389:6379"
    volumes:
      - redis_data:/data
    networks:
      - panteon_network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: [ "npm", "start" ]
    depends_on:
      - postgres
      - redis
    networks:
      - panteon_network


volumes:
  postgres_data:
  redis_data:

networks:
  panteon_network:
